apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      version: blue
  template:
    metadata:
      labels:
        app: nodejs-app
        version: blue
    spec:
      containers:
      - name: nodejs-app
        image: nodejs-app:blue
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000