apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  namespace: blue-green-demo
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: blue-green-demo
    deployColor: blue
