jenkins:
  controller:
    admin:
      username: "admin"
      password: "admin123"
    
    ingress:
      enabled: false
    
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1"
    
    installPlugins:
      - kubernetes
      - workflow-aggregator
      - git
      - configuration-as-code
      - job-dsl
      - blueocean
      - blueocean-dashboard
      - blueocean-autofavorite
      - credentials-binding
      - docker-workflow
      - sonar

    installLatestPlugins: true
    
    # java Options
    javaOpts: "-Xmx2048m"

    # Enable Jenkins Configuration as Code (JCasC)
    JCasC:
      enabled: true
      defaultConfig: true
    
  agent:
    enabled: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    
  rbac:
    create: true

  serviceAccount:
    create: true
    name: jenkins
